services:
  - type: web
    name: rekono-backend
    env: node
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: node --max-old-space-size=256 dist/main
    healthCheckPath: /v1/auth/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
